services:
  db:
    image: postgres:${POSTGRES_TAG:-16-alpine}
    container_name: kubeop-db
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - dbdata:/var/lib/postgresql/data

  manager:
    image: ${KUBEOP_MANAGER_IMAGE:-ghcr.io/vaheed/kubeop/manager-dev:dev}
    container_name: kubeop-manager
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${KUBEOP_MANAGER_PORT:-18080}:8080"
    healthcheck:
      test: ["CMD", "/hc"]
      interval: 10s
      timeout: 3s
      retries: 20
      start_period: 5s

volumes:
  dbdata: {}
