apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: kubeop-operator
  namespace: kubeop-system
spec:
  minAvailable: {{ .Values.pdb.minAvailable | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: kubeop-operator

