apiVersion: v1
kind: Service
metadata:
  name: kubeop-operator-metrics
  namespace: kubeop-system
  labels:
    app.kubernetes.io/name: kubeop-operator
  {{- with .Values.metrics.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
    - name: http-metrics
      port: 8081
      targetPort: metrics
  selector:
    app.kubernetes.io/name: kubeop-operator
