apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dnsrecords.paas.kubeop.io
spec:
  group: paas.kubeop.io
  scope: Cluster
  names:
    kind: DNSRecord
    plural: dnsrecords
    singular: dnsrecord
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                host:
                  type: string
                target:
                  type: string
            status:
              type: object
              properties:
                ready:
                  type: boolean
                message:
                  type: string
      additionalPrinterColumns:
        - name: Host
          type: string
          jsonPath: .spec.host
        - name: Ready
          type: string
          jsonPath: .status.ready
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp

