apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: policies.paas.kubeop.io
spec:
  group: paas.kubeop.io
  scope: Cluster
  names:
    kind: Policy
    plural: policies
    singular: policy
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                egressAllowCIDRs:
                  type: array
                  items:
                    type: string
              x-kubernetes-validations:
                - rule: "!has(self.egressAllowCIDRs) || size(self.egressAllowCIDRs) <= 64"
                  message: "egressAllowCIDRs list too large"
      additionalPrinterColumns:
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
