apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: apps.paas.kubeop.io
spec:
  group: paas.kubeop.io
  scope: Namespaced
  names:
    kind: App
    plural: apps
    singular: app
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                type:
                  type: string
                  enum: [Image, Git, Helm, Raw]
                image:
                  type: string
                host:
                  type: string
              x-kubernetes-validations:
                - rule: "self.type == 'Image' ? has(self.image) : true"
                  message: "spec.image required when type=Image"
            status:
              type: object
              properties:
                ready:
                  type: boolean
                revision:
                  type: string
                conditions:
                  type: array
                  items:
                    type: object
      additionalPrinterColumns:
        - name: Type
          type: string
          jsonPath: .spec.type
        - name: Host
          type: string
          jsonPath: .spec.host
        - name: Ready
          type: string
          jsonPath: .status.conditions[?(@.type=="Ready")].status
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
