apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: registries.paas.kubeop.io
spec:
  group: paas.kubeop.io
  scope: Cluster
  names:
    kind: Registry
    plural: registries
    singular: registry
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                host:
                  type: string
                username:
                  type: string
                passwordRef:
                  type: string
              x-kubernetes-validations:
                - rule: "has(self.host) && size(self.host) > 0"
                  message: "spec.host is required"
                - rule: "!(has(self.username)) || has(self.passwordRef)"
                  message: "spec.passwordRef must be set when username provided"
      additionalPrinterColumns:
        - name: Host
          type: string
          jsonPath: .spec.host
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
