apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: projects.paas.kubeop.io
spec:
  group: paas.kubeop.io
  scope: Cluster
  names:
    kind: Project
    plural: projects
    singular: project
    shortNames:
      - proj
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                tenantRef:
                  type: string
                  minLength: 1
                name:
                  type: string
                  minLength: 1
              x-kubernetes-validations:
                - rule: "has(self.tenantRef) && size(self.tenantRef) > 0"
                  message: "spec.tenantRef is required"
                - rule: "has(self.name) && size(self.name) > 0"
                  message: "spec.name is required"
            status:
              type: object
              properties:
                namespace:
                  type: string
                ready:
                  type: boolean
                conditions:
                  type: array
                  items:
                    type: object
      additionalPrinterColumns:
        - name: Namespace
          type: string
          jsonPath: .status.namespace
        - name: Ready
          type: string
          jsonPath: .status.conditions[?(@.type=="Ready")].status
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
