apiVersion: paas.kubeop.io/v1alpha1
kind: RegistryCredential
metadata:
  name: sample-registry
  labels:
    paas.kubeop.io/tenant: sample-tenant
spec:
  type: dockerHub
  secretRef: registry-auth
  tenantRef: sample-tenant
