ARG GOLANG_BASE=golang:1.24-alpine3.20
ARG DISTROLESS_BASE=gcr.io/distroless/static:nonroot
FROM ${GOLANG_BASE} AS build
WORKDIR /src
RUN apk add --no-cache ca-certificates git build-base
COPY go.mod go.sum* ./
RUN go mod download || true
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags "-s -w" -o /out/acmemock ./cmd/acmemock

FROM ${DISTROLESS_BASE}
COPY --from=build /out/acmemock /acmemock
USER 65532:65532
EXPOSE 8080
ENTRYPOINT ["/acmemock"]
