-- Add soft-delete columns
ALTER TABLE IF NOT EXISTS users ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;
ALTER TABLE IF NOT EXISTS projects ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;
ALTER TABLE IF NOT EXISTS apps ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;

