CREATE TABLE IF NOT EXISTS usage_raw (
    id BIGSERIAL PRIMARY KEY,
    ts TIMESTAMPTZ NOT NULL,
    tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    cpu_milli BIGINT NOT NULL DEFAULT 0,
    mem_mib  BIGINT NOT NULL DEFAULT 0
);

