extends: substitution
message: "Use '%s' instead of '%s'."
level: warning
description: "Ensure consistent product terminology."
ignorecase: true
scope: text
swap:
  '\\bkubeop\\b': kubeOP
  '\\bKubeOp\\b': kubeOP
  '\\bKubeop\\b': kubeOP
  kubeop.io: kubeOP.io
