apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeop-admission
  labels:
    app.kubernetes.io/name: kubeop-admission
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: kubeop-admission
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kubeop-admission
    spec:
      containers:
        - name: admission
          image: "{{ .Values.image.repository }}{{ if .Values.image.digest }}@{{ .Values.image.digest }}{{ else }}:{{ .Values.image.tag }}{{ end }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: KUBEOP_IMAGE_ALLOWLIST
              value: "{{ .Values.policy.imageAllowlist }}"
            - name: KUBEOP_EGRESS_BASELINE
              value: "{{ .Values.policy.egressBaseline }}"
          ports:
            - name: https
              containerPort: 8443
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /readyz
              port: https
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: https

