apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeop-manager
  labels:
    app.kubernetes.io/name: kubeop-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kubeop-manager
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kubeop-manager
    spec:
      containers:
        - name: manager
          image: "{{ .Values.image.repository }}{{ if .Values.image.digest }}@{{ .Values.image.digest }}{{ else }}:{{ .Values.image.tag }}{{ end }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- range $k, $v := .Values.env }}
            - name: {{ $k }}
              value: "{{ $v }}"
            {{- end }}
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
          livenessProbe:
            httpGet:
              path: /healthz
              port: http

